# Generated by Django 3.2.9 on 2021-11-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='logo',
            field=models.FileField(upload_to='clients/'),
        ),
    ]
